/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

@SuppressWarnings("unused")
public class Book extends org.asn1gen.runtime.java.AsnSequence {
  public static final Book EMPTY = new Book(
    org.asn1gen.runtime.java.AsnOctetString.EMPTY,
    org.asn1gen.runtime.java.AsnOctetString.EMPTY,
    org.asn1gen.runtime.java.AsnOctetString.EMPTY,
    BookCover.EMPTY,
    org.asn1gen.runtime.java.AsnBoolean.EMPTY);

  /*GenJava.scala:411*/public final org.asn1gen.runtime.java.AsnOctetString isbn;
  public final org.asn1gen.runtime.java.AsnOctetString title;
  public final org.asn1gen.runtime.java.AsnOctetString author;
  public final BookCover cover;
  public final org.asn1gen.runtime.java.AsnBoolean isInPrint;

  public Book(
      /*GenJava.scala:1410*/final org.asn1gen.runtime.java.AsnOctetString isbn,
      final org.asn1gen.runtime.java.AsnOctetString title,
      final org.asn1gen.runtime.java.AsnOctetString author,
      final BookCover cover,
      final org.asn1gen.runtime.java.AsnBoolean isInPrint) {
    /*GenJava.scala:1400*/this.isbn = isbn;
    this.title = title;
    this.author = author;
    this.cover = cover;
    this.isInPrint = isInPrint;
  }

  public final Book withIsbn(final org.asn1gen.runtime.java.AsnOctetString value) {
    return new Book(
      value,
      this.title,
      this.author,
      this.cover,
      this.isInPrint);
  }

  public final Book withTitle(final org.asn1gen.runtime.java.AsnOctetString value) {
    return new Book(
      this.isbn,
      value,
      this.author,
      this.cover,
      this.isInPrint);
  }

  public final Book withAuthor(final org.asn1gen.runtime.java.AsnOctetString value) {
    return new Book(
      this.isbn,
      this.title,
      value,
      this.cover,
      this.isInPrint);
  }

  public final Book withCover(final BookCover value) {
    return new Book(
      this.isbn,
      this.title,
      this.author,
      value,
      this.isInPrint);
  }

  public final Book withIsInPrint(final org.asn1gen.runtime.java.AsnBoolean value) {
    return new Book(
      this.isbn,
      this.title,
      this.author,
      this.cover,
      value);
  }

  public boolean equals(final Book that) {
    assert that != null;
    /*GenJava.scala:464*/
    if (!this.isbn.equals(that.isbn)) {
      return false;
    }

    if (!this.title.equals(that.title)) {
      return false;
    }

    if (!this.author.equals(that.author)) {
      return false;
    }

    if (!this.cover.equals(that.cover)) {
      return false;
    }

    if (!this.isInPrint.equals(that.isInPrint)) {
      return false;
    }

    return true;
  }

  @Override
  public boolean equals(final Object that) {
    if (that instanceof Book) {
      return this.equals((Book)that);
    }

    return true;
  }

  @Override
  public int hashCode() {
    return (0
      ^ this.isbn.hashCode()
      ^ this.title.hashCode()
      ^ this.author.hashCode()
      ^ this.cover.hashCode()
      ^ this.isInPrint.hashCode());
  }
}

