/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

@SuppressWarnings("unused")
public class Items extends org.asn1gen.runtime.java.AsnList {
  public static Items EMPTY = new Items(org.asn1gen.runtime.java.ConsList.<Item>nil());

  public final org.asn1gen.runtime.java.ConsList<Item> items;

  public Items(final org.asn1gen.runtime.java.ConsList<Item> items) {
    this.items = items;
  }

  public Items withItems(final org.asn1gen.runtime.java.ConsList<Item> value) {
    return new Items(value);
  }

  public boolean equals(final Items that) {
    assert that != null;

    return this.items.equals(that.items);
  }

  public boolean equals(final Object that) {
    if (that instanceof Items) {
      return this.equals((Items)that);
    }

    return true;
  }

  @Override
  public int hashCode() {
    return this.items.hashCode();
  }
}

