/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

@SuppressWarnings("unused")
public abstract class Item extends org.asn1gen.runtime.java.AsnChoice {
  /*GenJava.scala:348*/
  public static final Item_book EMPTY = Item_book.EMPTY;
  /*GenJava.scala:1529*/
  public Option<Book> getBook() {
    return None.instance();
  }

  public Option<Journal> getJournal() {
    return None.instance();
  }
  /*GenJava.scala:1505*/
  public Item_book withBook(final Book value) {
    return new Item_book(value);}

  public Item_journal withJournal(final Journal value) {
    return new Item_journal(value);}
}
/*GenJava.scala:368*//*GenJava.scala:1426*//*GenJava.scala:1426*/
