/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

@SuppressWarnings("unused")
public class Journals extends org.asn1gen.runtime.java.AsnList {
  public static Journals EMPTY = new Journals(org.asn1gen.runtime.java.ConsList.<Journal>nil());

  public final org.asn1gen.runtime.java.ConsList<Journal> items;

  public Journals(final org.asn1gen.runtime.java.ConsList<Journal> items) {
    this.items = items;
  }

  public Journals withItems(final org.asn1gen.runtime.java.ConsList<Journal> value) {
    return new Journals(value);
  }

  public boolean equals(final Journals that) {
    assert that != null;

    return this.items.equals(that.items);
  }

  public boolean equals(final Object that) {
    if (that instanceof Journals) {
      return this.equals((Journals)that);
    }

    return true;
  }

  @Override
  public int hashCode() {
    return this.items.hashCode();
  }
}

