/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

@SuppressWarnings("unused")
public class Journal extends org.asn1gen.runtime.java.AsnSequence {
  public static final Journal EMPTY = new Journal(
    org.asn1gen.runtime.java.AsnOctetString.EMPTY,
    org.asn1gen.runtime.java.AsnOctetString.EMPTY);

  /*GenJava.scala:411*/public final org.asn1gen.runtime.java.AsnOctetString title;
  public final org.asn1gen.runtime.java.AsnOctetString edition;

  public Journal(
      /*GenJava.scala:1410*/final org.asn1gen.runtime.java.AsnOctetString title,
      final org.asn1gen.runtime.java.AsnOctetString edition) {
    /*GenJava.scala:1400*/this.title = title;
    this.edition = edition;
  }

  public final Journal withTitle(final org.asn1gen.runtime.java.AsnOctetString value) {
    return new Journal(
      value,
      this.edition);
  }

  public final Journal withEdition(final org.asn1gen.runtime.java.AsnOctetString value) {
    return new Journal(
      this.title,
      value);
  }

  public boolean equals(final Journal that) {
    assert that != null;
    /*GenJava.scala:464*/
    if (!this.title.equals(that.title)) {
      return false;
    }

    if (!this.edition.equals(that.edition)) {
      return false;
    }

    return true;
  }

  @Override
  public boolean equals(final Object that) {
    if (that instanceof Journal) {
      return this.equals((Journal)that);
    }

    return true;
  }

  @Override
  public int hashCode() {
    return (0
      ^ this.title.hashCode()
      ^ this.edition.hashCode());
  }
}

