/* This file was generated by asn1gen */

package moo.codec.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

import moo.model.ASNEXAMPLES.*;
import static org.asn1gen.runtime.java.AsnToBer.*;
import static moo.codec.ASNEXAMPLES.AsnToBer.*;

@SuppressWarnings("unused")
public class AsnToBerShadow {

  public static BerWriter encodePart_(final Books value) throws AsnException {
    BerWriter dataWriter = BerWriter.EMPTY;

    for (final Book item: value.items) {
      dataWriter = dataWriter.then(encode(item));
    }

    return dataWriter;
  }

  public static BerWriter encode_(final Books value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final BookPrice value) throws AsnException {
    return BerWriter.EMPTY
        .then(encode(value.isbn))
        .then(encode(value.price));
  }

  public static BerWriter encode_(final BookPrice value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final BookPrices value) throws AsnException {
    BerWriter dataWriter = BerWriter.EMPTY;

    for (final Book item: value.items) {
      dataWriter = dataWriter.then(encode(item));
    }

    return dataWriter;
  }

  public static BerWriter encode_(final BookPrices value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final BookCover value) throws AsnException {
    return encodePart(value.value);
  }

  public static BerWriter encode_(final BookCover value) throws AsnException {
    final BerWriter dataWriter = encodePart(value.value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.PRIMITIVE, 10).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final Book value) throws AsnException {
    return BerWriter.EMPTY
        .then(encode(value.isbn))
        .then(encode(value.title))
        .then(encode(value.author))
        .then(encode(value.cover))
        .then(encode(value.isInPrint));
  }

  public static BerWriter encode_(final Book value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final Journals value) throws AsnException {
    BerWriter dataWriter = BerWriter.EMPTY;

    for (final Journal item: value.items) {
      dataWriter = dataWriter.then(encode(item));
    }

    return dataWriter;
  }

  public static BerWriter encode_(final Journals value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final Item value) throws AsnException {
    switch (value.choiceId()) {
    case 1:
      return encodePart((Book)value.element());
    case 2:
      return encodePart((Journal)value.element());
    default:
      throw new AsnException();
    }
  }

  public static BerWriter encode_(final Item value) throws AsnException {
    final BerWriter dataWriter = encode(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.PRIMITIVE, value.choiceId()).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final Journal value) throws AsnException {
    return BerWriter.EMPTY
        .then(encode(value.title))
        .then(encode(value.edition));
  }

  public static BerWriter encode_(final Journal value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }

  public static BerWriter encodePart_(final Items value) throws AsnException {
    BerWriter dataWriter = BerWriter.EMPTY;

    for (final Item item: value.items) {
      dataWriter = dataWriter.then(encode(item));
    }

    return dataWriter;
  }

  public static BerWriter encode_(final Items value) throws AsnException {
    final BerWriter dataWriter = encodePart(value);

    return BerWriter.EMPTY.tag(AsnClass.UNIVERSAL, AsnForm.CONSTRUCTED, 17).length(dataWriter.length).then(dataWriter);
  }
}
